FROM alpine

ENV HELM_LATEST_VERSION="v2.14.3"

RUN apk add --update ca-certificates \
 && apk add --update -t deps wget git openssl bash \
 && wget https://storage.googleapis.com/kubernetes-helm/helm-${HELM_LATEST_VERSION}-linux-arm64.tar.gz \
 && tar -xvf helm-${HELM_LATEST_VERSION}-linux-arm64.tar.gz \
 && mv linux-arm64/helm /usr/local/bin \
 && apk del --purge deps \
 && rm /var/cache/apk/* \
 && rm -f /helm-${HELM_LATEST_VERSION}-linux-arm64.tar.gz

ENTRYPOINT ["helm"]
CMD ["help"]
